import type { Connector } from './types';

export const connectorCatalog: Connector[] = [
  {
    id: 'polymarket',
    name: 'Polymarket',
    tagline: 'Crypto-settled prediction markets on politics, macro, sports.',
    category: 'prediction',
    status: 'connected',
    logo: { mark: 'PM', bg: '#0E1F36', fg: '#2F6BFF' },
    capabilities: ['Order book', 'Live odds', 'USDC settle'],
    docsUrl: 'https://docs.polymarket.com',
  },
  {
    id: 'kalshi',
    name: 'Kalshi',
    tagline: 'CFTC-regulated event contracts — Fed, elections, climate.',
    category: 'prediction',
    status: 'connected',
    logo: { mark: 'K', bg: '#0F2A1F', fg: '#00C853' },
    capabilities: ['REST + WS', 'USD cash settle', 'Regulated'],
    docsUrl: 'https://trading-api.readme.io',
  },
  {
    id: 'tradingview',
    name: 'TradingView',
    tagline: 'Charting + webhook alerts routed through the MCP bridge.',
    category: 'charts',
    status: 'connected',
    logo: { mark: 'TV', bg: '#0E1D2E', fg: '#2962FF' },
    capabilities: ['Webhooks', 'Pine alerts', 'MCP bridge'],
    docsUrl: 'https://www.tradingview.com',
  },
  {
    id: 'alpaca',
    name: 'Alpaca',
    tagline: 'Commission-free US equities and options via paper or live keys.',
    category: 'equities',
    status: 'available',
    logo: { mark: 'AL', bg: '#0F1A14', fg: '#FFD400' },
    capabilities: ['Stocks', 'Options', 'Paper'],
    docsUrl: 'https://alpaca.markets/docs',
  },
  {
    id: 'ibkr',
    name: 'Interactive Brokers',
    tagline: 'Global equities, futures, options across 150+ markets.',
    category: 'equities',
    status: 'available',
    logo: { mark: 'IBKR', bg: '#1A1106', fg: '#D9202F' },
    capabilities: ['TWS API', 'Futures', 'Global'],
    docsUrl: 'https://www.interactivebrokers.com/api',
  },
  {
    id: 'binance',
    name: 'Binance',
    tagline: 'Deepest crypto spot + perp liquidity outside the US.',
    category: 'crypto',
    status: 'connected',
    logo: { mark: 'B', bg: '#1F1805', fg: '#F0B90B' },
    capabilities: ['Spot', 'Perp', 'WebSocket'],
    docsUrl: 'https://binance-docs.github.io',
  },
  {
    id: 'coinbase',
    name: 'Coinbase',
    tagline: 'US-regulated crypto exchange with Advanced Trade API.',
    category: 'crypto',
    status: 'available',
    logo: { mark: 'CB', bg: '#0B1A36', fg: '#0052FF' },
    capabilities: ['Spot', 'Advanced Trade', 'USD'],
    docsUrl: 'https://docs.cloud.coinbase.com',
  },
  {
    id: 'oanda',
    name: 'OANDA',
    tagline: 'Retail forex with 70+ pairs, CFD, and REST streaming.',
    category: 'forex',
    status: 'available',
    logo: { mark: 'OA', bg: '#1A0F12', fg: '#E8304A' },
    capabilities: ['FX spot', 'CFD', 'Streaming'],
    docsUrl: 'https://developer.oanda.com',
  },
  {
    id: 'metatrader',
    name: 'MetaTrader 5',
    tagline: 'Broker-agnostic FX bridge via the MT5 Python API.',
    category: 'forex',
    status: 'beta',
    logo: { mark: 'MT5', bg: '#0B1628', fg: '#26A1F1' },
    capabilities: ['FX', 'Indices', 'EA bridge'],
    docsUrl: 'https://www.mql5.com',
  },
  {
    id: 'dukascopy',
    name: 'Dukascopy',
    tagline: 'Swiss-regulated FX with tick-level historical data.',
    category: 'forex',
    status: 'available',
    logo: { mark: 'DK', bg: '#1A1A1A', fg: '#FFFFFF' },
    capabilities: ['FX', 'Tick data', 'JForex'],
    docsUrl: 'https://www.dukascopy.com',
  },
  {
    id: 'robinhood',
    name: 'Robinhood',
    tagline: 'Retail equities, options, and crypto through the unofficial API.',
    category: 'equities',
    status: 'beta',
    logo: { mark: 'RH', bg: '#0A1A0A', fg: '#8FD14F' },
    capabilities: ['Stocks', 'Options', 'Crypto'],
    docsUrl: 'https://robinhood.com',
  },
  {
    id: 'draftkings',
    name: 'DraftKings',
    tagline: 'Sportsbook prices for cross-market prediction hedging.',
    category: 'sportsbook',
    status: 'available',
    logo: { mark: 'DK', bg: '#0A1F0A', fg: '#53D337' },
    capabilities: ['Odds feed', 'Lines', 'Props'],
    docsUrl: 'https://www.draftkings.com',
  },
];

export const categoryLabels: Record<Connector['category'], string> = {
  prediction: 'Prediction markets',
  equities: 'Equities & options',
  crypto: 'Crypto exchanges',
  forex: 'Forex brokers',
  charts: 'Charts & signals',
  sportsbook: 'Sportsbook',
};
